require 'rubygems'
require 'hoe'
require './lib/perro.rb'

Hoe.new('perro', Perro::VERSION) do |p|
  p.name = "perro"
  p.developer('carlos', 'carlosrr@gmail.com')
  p.summary = "A quick and dirty solution for serving files easily."
  p.extra_deps = [ ["mongrel", ">= 1.1.4"] , ["haml" , ">= 2.0.3"] ]
end
